const SHOW_CALCULATOR_SCREEN = "SHOW_CALCULATOR_SCREEN";
const SHOW_WORKERS_SCREEN = "SHOW_WORKERS_SCREEN";
const SHOW_EDITION_SCREEN = "SHOW_EDITION_SCREEN";

export default {
	SHOW_CALCULATOR_SCREEN,
	SHOW_WORKERS_SCREEN,
	SHOW_EDITION_SCREEN,
};
