const ADD_DEPARTMENT = "ADD_DEPARTMENT";
const ADD_DEPARTMENT_WITH_DB = "ADD_DEPARTMENT_WITH_DB";
const ADD_POSITION_TO_DEPARTMENT = "ADD_POSITION_TO_DEPARTMENT"
const ADD_POSITION_TO_DEPARTMENT_WITH_DB = "ADD_POSITION_TO_DEPARTMENT_WITH_DB"
const RESET_DEPARTMENTS = "RESET_DEPARTMENTS"
const DELETE_DEPARTMENT = "DELETE_DEPARTMENT"
const DELETE_DEPARTMENT_WITH_DB = "DELETE_DEPARTMENT_WITH_DB"
const EDIT_DEPARTMENT_NAME = "EDIT_DEPARTMENT_NAME"
const RESET_POSITIONS_IN_DEPARTMENT = "RESET_POSITIONS_IN_DEPARTMENT"
const DELETE_POSITION_IN_DEPARTMENT = "DELETE_POSITION_IN_DEPARTMENT"
const EDIT_POSITION_NAME_IN_DEPARTMENT = "EDIT_POSITION_NAME_IN_DEPARTMENT"
const EDIT_POSITION_NAME_IN_DEPARTMENT_WTIH_DB = "EDIT_POSITION_NAME_IN_DEPARTMENT_WTIH_DB"
const EDIT_POSITION_COUNT_IN_DEPARTMENT = "EDIT_POSITION_COUNT_IN_DEPARTMENT"
const EDIT_POSITION_PRICE_IN_DEPARTMENT = "EDIT_POSITION_PRICE_IN_DEPARTMENT"
const EDIT_POSITION_PRICE_IN_DEPARTMENT_WITH_DB = "EDIT_POSITION_PRICE_IN_DEPARTMENT_WITH_DB"
const EDIT_POSITION_UNIT_IN_DEPARTMENT = "EDIT_POSITION_UNIT_IN_DEPARTMENT"
const EDIT_POSITION_UNIT_IN_DEPARTMENT_WITH_DB = "EDIT_POSITION_UNIT_IN_DEPARTMENT_WITH_DB"
const DELETE_POSITION_IN_DEPARTMENT_WITH_DB = "DELETE_POSITION_IN_DEPARTMENT_WITH_DB"
const MOVE_POSITION_TO_ANOTHER_DEPARTMENT = "MOVE_POSITION_TO_ANOTHER_DEPARTMENT"
const EDIT_WHOLE_POSITION_IN_DB = "EDIT_WHOLE_POSITION_IN_DB"
const INITIALIZE_ADDITIONAL_COSTS = "INITIALIZE_ADDITIONAL_COSTS"
const ADD_ADDITIONAL_COSTS = "ADD_ADDITIONAL_COSTS"
const RESET_ADDITIONAL_COSTS = "RESET_ADDITIONAL_COSTS"
const DELETE_ADDITIONAL_COST = "DELETE_ADDITIONAL_COST"
const EDIT_ADDITIONALCOST_NAME = "EDIT_ADDITIONALCOST_NAME"
const EDIT_ADDITIONALCOST_AMOUNT = "EDIT_ADDITIONALCOST_AMOUNT"
const EDIT_ADDITIONALCOST_TYPE = "EDIT_ADDITIONALCOST_TYPE"
const RESET_ALL_COUNTS_AND_ADDITIONAL_COSTS = "RESET_ALL_COUNTS_AND_ADDITIONAL_COSTS"
const LOAD_DEPARTMENTS_STATE_FROM_JSON ="LOAD_DEPARTMENTS_STATE_FROM_JSON"
export default {
  ADD_DEPARTMENT,
  ADD_DEPARTMENT_WITH_DB,
  RESET_DEPARTMENTS,
  DELETE_DEPARTMENT,
  DELETE_DEPARTMENT_WITH_DB,
  EDIT_DEPARTMENT_NAME,
  ADD_POSITION_TO_DEPARTMENT,
  ADD_POSITION_TO_DEPARTMENT_WITH_DB,
  RESET_POSITIONS_IN_DEPARTMENT,
  DELETE_POSITION_IN_DEPARTMENT,
  EDIT_POSITION_NAME_IN_DEPARTMENT,
  EDIT_POSITION_COUNT_IN_DEPARTMENT,
  EDIT_POSITION_PRICE_IN_DEPARTMENT,
  EDIT_POSITION_UNIT_IN_DEPARTMENT,
  DELETE_POSITION_IN_DEPARTMENT_WITH_DB,
  MOVE_POSITION_TO_ANOTHER_DEPARTMENT,
  EDIT_POSITION_NAME_IN_DEPARTMENT_WTIH_DB,
  EDIT_POSITION_PRICE_IN_DEPARTMENT_WITH_DB,
  EDIT_POSITION_UNIT_IN_DEPARTMENT_WITH_DB,
  EDIT_WHOLE_POSITION_IN_DB,
  ADD_ADDITIONAL_COSTS,
  INITIALIZE_ADDITIONAL_COSTS,
  RESET_ADDITIONAL_COSTS,
  DELETE_ADDITIONAL_COST,
  EDIT_ADDITIONALCOST_NAME,
  EDIT_ADDITIONALCOST_AMOUNT,
  EDIT_ADDITIONALCOST_TYPE,
  RESET_ALL_COUNTS_AND_ADDITIONAL_COSTS,
  LOAD_DEPARTMENTS_STATE_FROM_JSON
}